version: "3.9"
services:
  web:
    build: .
    ports:
      - "5006:5006"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["python", "-m", "flask", "--app", "app", "run", "--host=0.0.0.0", "--port=5006", "--reload"]
    restart: unless-stopped
